menu/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('<str:menu_name>/', MenuView.as_view(), name='menu'),
    path('', index, name='index'),

]

menu/menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

menu/main/models.py
from django.db import models


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    url = models.CharField(max_length=255)

    def __str__(self):
        return self.name

menu/main/views.py
from django.shortcuts import render
from django.views import View
from .models import MenuItem


class MenuView(View):
    def get(self, request, menu_name):
        menu_items = MenuItem.objects.filter(name=menu_name)
        context = {'menu_items': menu_items}
        return render(request, 'main/menu.html', context)


def index(request):
    return render(request, 'main/index.html')

menu/main/templates/layout/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    {% block title %}<title>Django-menu</title>{% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

menu/main/templates/main/index.html
{% extends "layout/basic.html" %}
{% load menu_tags %}

{% block title %}<title>Django-menu-app</title>{% endblock %}

{% block content %}
<h1 class="display-5 text-center">Welcome !</h1>
<div class="container">
    <div class="row">
        <div class="col-6">{% draw_menu '1' %}</div>
        <div class="col-6">{% draw_menu '10' %}</div>
    </div>
</div>

{% endblock %}

menu/main/templates/main/menu.html
{% extends "layout/basic.html" %}
{% load menu_tags %}
{% block title %}<title>menu</title>{% endblock %}

{% block content %}
<div class="col-6 m-4">
    <ul class="nav nav-pills">
        <div class="list-group">
            {% for menu_item in menu_items %}
            {% with request.path|slice:"1:-1" as path %}
            {% if menu_item.url == path %}
            <li class="nav-item active">
                <a class="list-group-item list-group-item-action active" aria-current="true"
                   href="{% url 'main:menu' menu_item.url %}">{{ menu_item.name }}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="list-group-item list-group-item-action" href="{% url 'main:menu' menu_item.url %}">
                    {{ menu_item.name }}</a>
            </li>
            {% endif %}
            {% if menu_item.children.all %}
            <ul>
                {% draw_children menu_item %}
            </ul>
            {% endif %}
            </li>
            {% endwith %}
            {% endfor %}
        </div>
    </ul>
</div>
{% endblock %}

menu/main/templates/main/menu_children.html
{% extends "layout/basic.html" %}
{% load menu_tags %}
{% block title %}<title>menu children</title>{% endblock %}

{% block content %}
<div class="col-6 m-4">
    <ul class="nav nav-pills">
        <div class="list-group">
            {% for child in menu_item.children.all %}
            {% with request.path|slice:"1:-1" as path %}
            {% if child.url == path %}
            <li class="nav-item active">
                <a class="list-group-item list-group-item-action active" aria-current="true"
                   href="{% url 'main:menu' child.url %}">{{ child.name }}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="list-group-item list-group-item-action" href="{% url 'main:menu' child.url %}">
                    {{ child.name }}</a>
            </li>
            {% endif %}
            {% if child.children.all %}
            <ul>
                {% draw_children child %}
            </ul>
            {% endif %}
            {% endwith %}
            {% endfor %}
        </div>
    </ul>
</div>
{% endblock %}